default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: Black code formatter
-   repo: https://github.com/PyCQA/pylint
    rev: v2.8.3
    hooks:
    -   id: pylint
        name: Pylint code linter
        files: ^nest/
        additional_dependencies: [matplotlib, numpy, tqdm, aiocoap]
